language: ruby
rvm:
 - 2.4.1
cache:
  bundler: true
  # Test Caching is good.
  # See: https://docs.travis-ci.com/user/caching/
services:
  - postgresql
addons:
    postgresql: "9.6"
before_script:
    - psql -c 'create database pf_companion_test;' -U postgres

