default: &default
  adapter: postgresql
  # adapter: mysql2
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  <<: *default
  database: pf_companion_development

test:
  <<: *default
  database: pf_companion_test

production:
  <<: *default
  database: pf_companion_production
  # username: pf_companion
  # password: <%= ENV['PF_COMPANION_DATABASE_PASSWORD'] %>
